services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_reto56
    environment:
      SA_PASSWORD: "ContraseñaFuerte123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - sql_data:/var/opt/mssql

  jupyter:
    build: ./jupyter
    container_name: jupyter_data_lab
    ports:
      - "8889:8888"
    volumes:
      - ../:/home/jovyan/work
    depends_on:
      - sqlserver

volumes:
  sql_data:
